### PR TITLE
Add CircleCI build

### PR DESCRIPTION
**Pull request by brendanlong**
If you merge this and then add this project in CircleCI, you'll get CI builds with basically no effort. We could make it faster by making a custom base image, but for a build that takes 3.5 minutes, it doesn't seem worth the effort.

### CODE REVIEW

**Comment by brendanlong** [comment]
(Made this as I started working on a driver using FreeTDS)

**Comment by brendanlong** [comment]
Hm I couldn't get the tests to run MariaDB. I get errors like this:

```
#!/bin/bash -eo pipefail
echo "
    mariadb://test:test@localhost/test
    postgresql://test@localhost/test
    sqlite3::memory:
" > tests/uris.conf
opam config exec -- jbuilder runtest
Done: 379/394 (jobs: 4)  test_param alias tests/runtest (got signal SEGV)
(cd _build/default/tests && ./test_param.exe)
     bikereg alias tests/runtest (got signal SEGV)
(cd _build/default/tests && ./bikereg.exe)
Done: 385/394 (jobs: 3)test_parallel_lwt alias tests/runtest (got signal SEGV)
(cd _build/default/tests && ./test_parallel_lwt.exe)
test_sql_lwt alias tests/runtest (got signal SEGV)
(cd _build/default/tests && ./test_sql_lwt.exe)
Done: 387/394 (jobs: 1)test_sql_async alias tests/runtest (got signal SEGV)
(cd _build/default/tests && ./test_sql_async.exe)
                       
Exited with code 1
```

https://circleci.com/gh/brendanlong/ocaml-caqti/22

**Comment by paurkedal** [comment]
I think the issue with MariaDB is that it needs a later client library.  I think we need to add the appropriate repo from http://mirror.one.com/mariadb/repo/10.3 to the build process to get libmariadb3 version 10.*.

**Comment by brendanlong** [comment]
Hmm I can't get the mariadb stuff to work. Debian and Ubuntu both make it really difficult to install the client libraries in a way that the Mariadb OCaml library likes. If you're interested, I'd rather merge this how it is and add the MariaDB testing later when someone has the patience to figure it out.

**Comment by paurkedal** [comment]
Looks good. Thanks!

**Pull request merged**
