### PR TITLE
Postgres populate with copy mode

### LINKED ISSUE #26: Postgresql Copy Mode Support
Further to #24, I am now trying to work out the best way to insert large amounts of data into a `postgres` database quickly. Based on the documentation [here](https://www.postgresql.org/docs/current/populate.html), the best way to do this is to make use of the `COPY` command to stream in the data.

I have run some experiments, and the use of `COPY` speeds up data insertion by roughly 10x in the case of my data, so I definitely want to make use of it (although I guess it is not always this much of a speed up).

Unfortunately, `COPY` is a `postgres`-specific extension (which is supported by `ocaml-postgres` but unused by `caqti`). It seems there is an equivalent for [`mariadb`](https://mariadb.com/kb/en/library/load-data-infile/), but I haven't been able to find a convincing equivalent for `sqlite`.

This leads to a couple of questions:
* Do you think this is the sort of thing that `caqti` should be supporting, or should it live in application code?
* If so what do you think the best way to support it would be?

My opinion is that this would be a nice addition to `caqti`. I think that a good equivalent here is  transaction support, which seems to trigger different connection code based on the `can_transact` parameter in the `driver_info` for a given driver - maybe a `can_copy` parameter would allow the drivers to declare copy methods, and would raise an error if you tried to use them with a driver that did not support it? This would be combined with some new helper functions for `CONNECTION` objects.

I am happy to make a PR with and attempt at changes if you think this is worth pursuing.

### PR DESCRIPTION
**Pull request by leamingrad**
This PR updates the postgresql driver to use copy mode when the `populate` function is called, which should resolve #26.

The code is still slightly rough, but I can't see any obvious ways to make it clearer at this point - so any suggestions for that would be very welcome.

### CODE REVIEW

**Comment by paurkedal** [comment]
I'll take a closer look at this tomorrow, but one thing I noticed is that `Pg.Put_copy_not_queued` is not handled, which will be a common case when the OCaml code outperforms the network or DB.  I think we need to wait on the FD like done in `communicate` and `get_next_result`, but we should investigate to be sure.

**Comment by leamingrad** [comment]
Good spot - I have updated to handle `Put_copy_not_queued` based on `get_next_result`. It could potentially be refactored somehow so it is cleaner, but I decided not to do that for now to keep the MR cleaner.

**Comment by paurkedal** [comment]
I had a proper look now.  I think it looks generally good; the main missing piece is that the fields needs to be escaped (in both the text and csv formats).

Note that text and binary parameters need to be escaped differently. E.g. `\\x78797a` represents the byte sequence of `xyz` for a binary field and the literal text `\x78797a` for a text field.  If you stick with the CSV format, note also that the empty string must be quoted, otherwise it will be interpreted as `NULL`.  The text format uses `\N` for `NULL` and does not used quotes.  The other binary needs to be treated differently from text is to avoid coding errors or accidental recoding in case the client and server have different encoding.  I suggest renaming `binary_params` to `params` since it also contains text parameters, and to avoid confusion with my previous use of that variable name.

I adjusted the CI container to allow installation of the newest postgresql package, so please rebase your branch before the next push, so that we can see if it goes though.

Also, if you don't mind, could you try to imitate the existing coding style a bit better for the final version, esp. regarding `match` constructs (no space between "(" and "match", indent "|" one space from "(" if the match is parenthesized, and "->" on the line of the last pattern).

[1]: https://www.postgresql.org/docs/current/sql-copy.html

**Comment by leamingrad** [comment]
Thanks for the prompt feedback.

I have had a go at adding escaping, and have added some more testing to cover cases that would be broken if things are escaped incorrectly. Do you have any more examples of things to escape? In particular, I am not sure how to test the difference between text and binary fields you mention above.

I have tried to keep close to the original coding style, so let me know if there are further tweaks you would like made.

**Comment by paurkedal** [comment]
First, thanks for the rebase (CI passed now) and style tweaks.

To test the binary encoding, I would suggest adding a field to the test table.  The type is "bytea" for postgresql and "blob" for sqlite and mariadb.  If the column is made optional, I don't think the other tests need to be changed.  To test, populate, read back, and compare.  A fairly complete test would write all byte-string combinations up to two or three bytes systematically.  In that case, it may be better to use a dedicated table.  Trying the corner cases should suffice if it's easier.

I agree we should try to avoid the code duplication.  My original though was to go though the encoded parameters along with the `binary_params` array and escape as needed:  If the `binary_params` entry is set, use hex encoding, otherwise look for a character which needs escape, and escape if needed.  Another option would be to pass binary/text escaping functions as optional parameters to the encoder.  On the other hand, reimplementing the encoder could be the most efficient, esp. if it writes directly to a `Buffer.t`.  What do you think?

Your escaping function is smart, but will only work if we can be sure the quote character itself is not escaped.  Also, escape newlines even when quoting, since they are platform-specific.  So, I think it is necessary to scan on character at the time.  See the [copy  documentation][1] for the escaping requirements. I'll check the code to see if our interpretations match.  For escaping binary values, it seems like you can use `conn#escape_bytea`.  On the other hand it seems `conn#escape_string` is in only meant for pasting into SQL and does not take into account the need to escape backslashes in the CSV (or even text) representation.

[1]: https://www.postgresql.org/docs/current/sql-copy.html

**Comment by leamingrad** [comment]
Sorry about the delay in work on this PR from my end. I've been trying to get this to work, but I think I am now running into more basic issues with handling `Caqti_type.Octet` in postgres.

I've pushed a branch at https://github.com/leamingrad/ocaml-caqti/tree/octet_investigations to flag up a few problems (which might as well be merged if possible since it adds more test coverage). This extends the existing SQL tests to apply to octets too, and I get some strange failures on postgres (they seem to work fine on sqlite and I don't have a mariadb to test against).

The failures seem to imply that the encoding for non-populate functions isn't working in some way. In particular:

* Attempting to run `SELECT ?` with the parameter `\x00` fails with:

      Request to <postgresql://james@127.0.0.1:49909/test> failed: ERROR:  invalid byte sequence for encoding "UTF8": 0x00
       Query: "SELECT $1".

* Attempting to run the `test_table` function to store `two`, `three` and `five` then concatenate the retrieved values to get `two+three+five` fails because the result is actually `\x74776f+\x7468726565+\x66697665`

The fix for the latter issue seems to be checking whether we are expecting binary params when retrieving the query - I think we just need to call `unescape_bytea` when decoding as per https://github.com/mmottl/postgresql-ocaml/blob/65e0b165b907920ea48a4fce6e1f59ac2b232cc2/examples/binary.ml#L46.

I am less sure about the former - interestingly, when I change `test_table` to send in `"\00"` as one of the octet strings, this works as expected. As far as I understand, parameter escaping is performed for all queries, but maybe I have missed something.

Maybe it would be easier/more reliable to perform all escaping ourselves in `encode_field` rather than relying on passing `binary_params`?

Do you think it is worth trying to get this resolved before progressing with this PR - and if so, should this happen here or somewhere else?

**Comment by paurkedal** [comment]
Thanks for investigating the issues with the binary parameters. I'll look at it shortly.

**Comment by paurkedal** [comment]
I merged your octet investigations and fixed the issues. The issue with the parameter was due to missing cast in the test. PostgreSQL infers parameter types from the SQL code, but can't make the inference for identity queries like this, which also can cause issues with floats and integers. The result decoding, however, was a bug in the decoding function, and the solution was precisely as you pointed out.

**Comment by paurkedal** [comment]
I had a look at the rest of this PR again, and have a few more comments:

I assume you didn't mean to commit the commenting out of `test_expr` in the `test_sql.ml`?  The tests takes some time, I might consider using alcotest so one can filter them.

Not obligatory, but `all_bytes` can be generated with `init_list 256 (fun c -> String.make 1 (Char.chr c))` if we put the following somewhere at the top of the file or in `testkit.ml`:
 ```ocaml
    let init_list n f = (* List.init is available from OCaml 4.6.0 *)
      let rec loop acc i = if i < 0 then acc else loop (f i :: acc) (i - 1) in
      loop [] (n - 1)
```

And please keep lines no longer than 80 characters.

**Comment by leamingrad** [comment]
Thanks for the feedback - sorry for the poor state of the latest changes, they were actually me push so I could switch computers.

I think I have now resolved all of your points, so this should be ready for another re-review. I might have got a bit overzealous with making every line under 80 characters, so I'm happy to remove stuff as required. Thanks in advance for all the time you are putting in to reviewing and helping this PR.

The reason I was commenting out `test_expr` is actually because this test always fails when testing against postgres for me as I have a non-UTC timezone on my computer - but that is outside the scope of this PR.

**Comment by paurkedal** [comment]
There is no overzealous in keeping lines below 81 columns, as far as I'm concerned, so can you please also do the remaining ones?  Esp. the new comments should be easy to re-flow to width 80.  I can do it after merging, but it tends to obscure authorship.

I noticed one more thing, I think we should handle the `Put_copy_not_queued` case for `#put_copy_end` the same way as for `#put_copy_data`.

I was originally worried about `escape_and_quote`, but I can see ESCAPE and QUOTE are by default double-quote for CSV, so this should be correct. A good test string to include may be `"\\\""`.

Otherwise, this looks good.

**Comment by leamingrad** [comment]
Cool - this should all be addressed now

**Comment by paurkedal** [comment]
I added one commit which simplifies the query string construction for populate, as you don't need to go though the request here. I also made a few stylistic tweaks. You can squash the commits if you wish. If you include my commit, which is okay too, make sure you are still Git author.  But I don't have a strong preference, so I'll merge this as-is otherwise.

**Comment by leamingrad** [comment]
I've squashed all the commits together so it is easier to blame in the future.

Looks like the CI is failing due to the issue that will be resolved by https://github.com/ocaml/opam-repository/pull/15435 - I guess it can be retried when that is merged

**Comment by paurkedal** [comment]
Perfect!  I noticed the CI failure too, but we've tested it, and I've run `dune-workspace.dev` locally, which succeeded, apart from on switch which exposed a missing version constraint for async and core.

**Comment by leamingrad** [comment]
Excellent thanks - could we get a new version with this change in it?

**Comment by paurkedal** [comment]
Sure, is next week soon enough?

**Comment by leamingrad** [comment]
Yes that will be fine thanks

**Comment by paurkedal** [comment]
This is now released as caqti-driver-postgresql.1.2.1.  Thanks for the help!

**Pull request merged**
