### PR TITLE
add method exec_count to Caqti_connection_sig.S

### PR DESCRIPTION
**Pull request by jabot2**
This PR adds a convenience method for update and delete statements where one wants to check whether any changes happened to the db.

### CODE REVIEW

**Comment by paurkedal** [comment]
I'm a reluctant to add convenience functions unless it is a common use case. Though, with your other PR is merged, we have coverage for affected_count for the supported DBs, so using it becomes more attractive. Two things:

Is it clear enough which count we're talking about, or should it be `exec_with_affected_count`?  It's a bit long, so I'll accept as-is if you prefer.

When I merge #46, can you rebase and add a test case for `exec_count`?  That will also verify that the implementations work and return the same result.

**Comment by jabot2** [comment]
Thanks for the feedback.

I'm not overly attached to the current name, so i will rename the method if i don't come up with a better name.

I will rebase this PR after you merge https://github.com/paurkedal/ocaml-caqti/pull/46 , and i will try to add a test case.

**Comment by jabot2** [comment]
so instead of rebasing, i merged the branch of the other PR.
If that is a problem for you i can squash the changes and create a new PR

**Comment by paurkedal** [comment]
GitHub has an option of rebasing before merging, which worked as intended, except it also eliminated the final merge commit.

Thanks for the contribution!

**Comment by jabot2** [comment]
You're welcome :-)

**Pull request merged**
